// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoNApi.Context;

#nullable disable

namespace ProyectoNApi.Migrations
{
    [DbContext(typeof(ProyectoNContext))]
    [Migration("20261002124159_AddPathologyTable")]
    partial class AddPathologyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoNApi.Entities.AnthropometricMeasurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurementId"));

                    b.Property<decimal?>("AbdominalSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BicipitalSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Calf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ContractedArm")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FatPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FrontThighSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Hip")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MedialCalfSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MusclePercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Observations")
                        .HasColumnType("numeric");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RelaxedArm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SubscapularSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SuprailiacSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SupraspinalSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Thigh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TricipitalSkinfold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Wrist")
                        .HasColumnType("numeric");

                    b.HasKey("MeasurementId");

                    b.HasIndex("PatientId");

                    b.ToTable("AnthropometricMeasurement");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Reminder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FoodId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealId"));

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipe")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("TimeInMinutes")
                        .HasColumnType("time without time zone");

                    b.HasKey("MealId");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.MealFood", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityInGrams")
                        .HasColumnType("numeric");

                    b.HasKey("MealId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("MealFood");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Nutrient", b =>
                {
                    b.Property<int>("NutrientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NutrientId"));

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ReferenceIntake")
                        .HasColumnType("numeric");

                    b.HasKey("NutrientId");

                    b.ToTable("Nutrient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutrientFood", b =>
                {
                    b.Property<int>("NutrientId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QuantityPer100g")
                        .HasColumnType("numeric");

                    b.HasKey("NutrientId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("NutrientFood");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutritionalPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionalPlan");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutritionalPlanMeal", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MealId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("NutritionalPlanMeal");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Pathology", b =>
                {
                    b.Property<int>("PathologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PathologyId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PathologyId");

                    b.ToTable("Pathology");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatientId"));

                    b.Property<bool>("AlcoholConsumption")
                        .HasColumnType("boolean");

                    b.Property<string>("Approach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FloorOrDoor")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<string>("SpecialDiet")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("text");

                    b.Property<bool>("TobaccoConsumption")
                        .HasColumnType("boolean");

                    b.HasKey("PatientId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.PatientPathology", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("PathologyId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DiagnosedDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("PatientId", "PathologyId");

                    b.HasIndex("PathologyId");

                    b.ToTable("PatientPathology");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.PatientUser", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("PatientId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PatientUser");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Restriction", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FoodId", "PatientId");

                    b.HasIndex("PatientId");

                    b.ToTable("Restriction");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TreatmentId"));

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TreatmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientTreatment");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.AnthropometricMeasurement", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("AnthropometricMeasurements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Appointment", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.MealFood", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Food", "Food")
                        .WithMany("MealFood")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.Meal", "Meal")
                        .WithMany("MealFood")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutrientFood", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Food", "Food")
                        .WithMany("NutrientFood")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.Nutrient", "Nutrient")
                        .WithMany("NutrientFood")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutritionalPlan", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("NutritionalPlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.User", "User")
                        .WithMany("NutritionalPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutritionalPlanMeal", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Meal", "Meal")
                        .WithMany("NutritionalPlanMeal")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.NutritionalPlan", "NutritionalPlan")
                        .WithMany("NutritionalPlanMeal")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("NutritionalPlan");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.PatientPathology", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Pathology", "Pathology")
                        .WithMany("PatientPathology")
                        .HasForeignKey("PathologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("PatientPathology")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pathology");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.PatientUser", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("PatientUsers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.User", "User")
                        .WithMany("PatientUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Restriction", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Food", "Food")
                        .WithMany("Restrictions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("Restrictions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Treatment", b =>
                {
                    b.HasOne("ProyectoNApi.Entities.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Food", b =>
                {
                    b.Navigation("MealFood");

                    b.Navigation("NutrientFood");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Meal", b =>
                {
                    b.Navigation("MealFood");

                    b.Navigation("NutritionalPlanMeal");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Nutrient", b =>
                {
                    b.Navigation("NutrientFood");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.NutritionalPlan", b =>
                {
                    b.Navigation("NutritionalPlanMeal");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Pathology", b =>
                {
                    b.Navigation("PatientPathology");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.Patient", b =>
                {
                    b.Navigation("AnthropometricMeasurements");

                    b.Navigation("Appointments");

                    b.Navigation("NutritionalPlans");

                    b.Navigation("PatientPathology");

                    b.Navigation("PatientUsers");

                    b.Navigation("Restrictions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("ProyectoNApi.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("NutritionalPlans");

                    b.Navigation("PatientUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
