using FluentValidation;
using Microsoft.EntityFrameworkCore;
using ProyectoNApi.Context;
using ProyectoNApi.Services;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddDbContext<ProyectoNContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddScoped<IUserService, UserService>();

// Add Swagger services
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Add OpenAPI services
builder.Services.AddOpenApi();

// Add CORS policy to allow frontend Next.js requests 
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowNextJs",
        policy =>
        {
            policy.WithOrigins("http://localhost:3000", "https://localhost:3000") // El puerto de tu Next.js
                  .AllowAnyHeader()
                  .AllowAnyMethod();
        });
});

// Add Validators
builder.Services.AddValidatorsFromAssemblyContaining<Program>();
builder.Services.AddControllers();

var app = builder.Build();

// Middleware from Swagger and OpenAPI only in Development
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    // Thisenables the graphic interface (/swagger)
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/openapi/v1.json", "ProyectoNApi v1"); // Connects the UI with the JSON route generated by .NET, ProyectoNApi v1 is the name that will appear in the drop-down menu of the version selector
        options.RoutePrefix = "swagger"; // The UI will be at https://localhost:7277/swagger
    });

     app.MapOpenApi(); // Maps the OpenAPI endpoint
}

app.UseHttpsRedirection();

// Activamos CORS después del build
app.UseCors("AllowNextJs");
app.MapControllers();

app.Run();


